# Generated by Django 3.1.2 on 2020-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logging',
            options={'verbose_name': 'Лог действий', 'verbose_name_plural': 'Логи действий'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон'),
        ),
        migrations.RemoveField(
            model_name='phones',
            name='updated',
        ),
        migrations.AddField(
            model_name='phones',
            name='updated',
            field=models.ManyToManyField(null=True, related_name='phones_logging', to='webui.Logging'),
        ),
    ]
