# Generated by Django 3.1.2 on 2020-10-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_auto_20201021_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='phone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='logging_phones', to='webui.phones'),
        ),
    ]
