# Generated by Django 3.1.2 on 2020-10-29 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0004_auto_20201021_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
